#!/usr/bin/env bash
# Commit-message convention check (ADVISORY by default).
#
# Encourages: "<type>: <imperative subject>" with subject <= 72 chars.
# Types: feat, fix, refactor, test, docs, chore, perf, build, ci, style, revert.
#
# Use as a git commit-msg hook (receives the message file path as $1) or standalone:
#   scripts/checks/commit-msg-check.sh .git/COMMIT_EDITMSG
#   echo "feat: add queue claim" | scripts/checks/commit-msg-check.sh
#
# STRICT_COMMIT_MSG=1 makes a violation non-zero (blocking).

set -uo pipefail

if [ "${1:-}" ] && [ -f "$1" ]; then
  subject="$(sed -n '1p' "$1")"
else
  subject="$(head -n1)"
fi

# Ignore merge/revert/fixup autogenerated messages.
case "$subject" in
  Merge\ *|Revert\ *|fixup!\ *|squash!\ *) echo "✓ commit-msg: skipped ($subject)"; exit 0 ;;
esac

ok=1
if ! printf '%s' "$subject" | grep -qE '^(feat|fix|refactor|test|docs|chore|perf|build|ci|style|revert)(\([a-z0-9_-]+\))?: .+'; then
  echo "⚠  commit-msg: subject should be '<type>: <summary>' (e.g. 'fix: prevent double-claim in queue')."
  ok=0
fi
if [ "${#subject}" -gt 72 ]; then
  echo "⚠  commit-msg: subject is ${#subject} chars (aim for <= 72)."
  ok=0
fi

if [ "$ok" -eq 1 ]; then
  echo "✓ commit-msg: OK."
  exit 0
fi
[ "${STRICT_COMMIT_MSG:-0}" = "1" ] && exit 1
exit 0
